AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  learning-network-v4

  Sample SAM Template for learning-network-v4

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  YourInfoFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: learning-network-v4-YourInfoFunction
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        YourInfo:
          Type: Api
          Properties:
            Path: /your-info
            Method: get
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: ./my-app
      Dockerfile: Dockerfile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  YourInfoApi:
    Description: "API Gateway endpoint URL for Prod stage for Your Info function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  YourInfoFunction:
    Description: "Your Info Lambda Function ARN"
    Value: !GetAtt YourInfoFunction.Arn
  YourInfoFunctionIamRole:
    Description: "Implicit IAM Role created for Your Info function"
    Value: !GetAtt YourInfoFunctionRole.Arn
