name: Daily Package Upgrades

on:
  schedule:
    - cron: "0 0-23/4 * * *"

jobs:
  upgrade-packages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"
          cache: "yarn"
      - name: Upgrade packages
        run: yarn upgrade
      - name: Commit changes
        run: |
          git config user.email ${{ github.actor }}@users.noreply.github.com
          git config user.name ${{ github.actor }}
          git add .
          git commit -m "Auto-upgraded packages $(date +'%Y-%m-%d %H:%M:%S')"
          git push
